AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation template for Portfolio UI - Development"
Transform: "AWS::Serverless-2016-10-31"

Parameters:
  ProjectName:
    Default: portfolio
    Description: "The name of the project. Will be used as prefix for resource names"
    Type: "String"
  BucketName:
    Description: "UI Bucket Asset"
    Type: "String"
  
Resources:

  UIBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: "index.html"
        ErrorDocument: "index.html"
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred

  UIBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref UIBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 
            - s3:GetObject
            Resource: !Sub arn:aws:s3:::${UIBucket}/*

  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "${ProjectName}-Dev-Stack"

  PortfolioFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Sub "${BucketName}.s3.amazonaws.com"
            Id: !Ref UIBucket
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}'
        Enabled: true
        Comment: !Sub "Cloudfront Distribution for ${ProjectName} UI - Development"
        DefaultRootObject: index.html
        CustomErrorResponses:
            - ErrorCode: 404
              ResponsePagePath: /index.html
              ResponseCode: 200
              ErrorCachingMinTTL: 0
            - ErrorCode: 403
              ResponsePagePath: /index.html
              ResponseCode: 200
              ErrorCachingMinTTL: 0
        DefaultCacheBehavior:
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          TargetOriginId: !Ref UIBucket
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_100

  PortfolioHeaderPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: !Sub ${AWS::StackName}-header-policy
        Comment: !Sub "Header policy for ${ProjectName} Development."
        CorsConfig:
          OriginOverride: false
          AccessControlAllowCredentials: false
          AccessControlAllowHeaders:
            Items:
              - "*"
          AccessControlAllowMethods:
            Items:
              - POST
              - GET
              - OPTIONS
              - DELETE
          AccessControlAllowOrigins:
            Items:
            - "*"
          AccessControlExposeHeaders:
            Items:
            - "*"
          AccessControlMaxAgeSec: 3600
        RemoveHeadersConfig:
          Items:
            - Header: server
        ServerTimingHeadersConfig:
          Enabled: true
          SamplingRate: 50
        SecurityHeadersConfig:
          StrictTransportSecurity:
            AccessControlMaxAgeSec: 31536000
            Override: true
          ContentTypeOptions:
            Override: true
          FrameOptions:
            FrameOption: SAMEORIGIN
            Override: true
          ReferrerPolicy:
            Override: true
            ReferrerPolicy: strict-origin-when-cross-origin
          XSSProtection:
            Override: true
            Protection: true

Outputs:
  UIBucket:
    Value: !Ref UIBucket
    Export:
      Name: !Sub "${AWS::StackName}-UIBucketName"
  CloudFrontDistributionID:
    Value: !Ref PortfolioFrontDistribution
    Export:
      Name: !Sub "${AWS::StackName}-DistributionID"
  CloudFrontURL:
    Value: !Sub "https://${PortfolioFrontDistribution.DomainName}"
    Export:
      Name: !Sub "${AWS::StackName}-CloudFrontURL"