AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation template for Portfolio UI - Development"
Transform: "AWS::Serverless-2016-10-31"

Parameters:
  ProjectName:
    Default: portfolio
    Description: "The name of the project. Will be used as prefix for resource names"
    Type: "String"
  SSLCertArnDev:
    Description: "ACM Cert arn for custom domain (Development)"
    Type: "String"
  HostnameDev:
    Description: "Hostname in DNS for ui (Development)"
    Type: "String"
  BucketName:
    Description: "UI Bucket Asset"
    Type: "String"
  
Resources:

  UIBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: "index.html"
        ErrorDocument: "index.html"
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred

  UIBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref UIBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 
            - s3:GetObject
            Resource: !Sub arn:aws:s3:::${UIBucket}/*

  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "${ProjectName}-Dev-Stack"

  PortfolioFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Sub "${BucketName}.s3.amazonaws.com"
            Id: !Ref UIBucket
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}'
        Aliases:
        - !Ref HostnameDev
        - !Sub "www.${HostnameDev}"
        Enabled: true
        Comment: !Sub "Cloudfront Distribution for ${ProjectName} UI - Development"
        DefaultRootObject: index.html
        CustomErrorResponses:
            - ErrorCode: 404
              ResponsePagePath: /index.html
              ResponseCode: 200
              ErrorCachingMinTTL: 0
            - ErrorCode: 403
              ResponsePagePath: /index.html
              ResponseCode: 200
              ErrorCachingMinTTL: 0
        DefaultCacheBehavior:
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          TargetOriginId: !Ref UIBucket
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
          ResponseHeadersPolicyId: !Ref PortfolioHeaderPolicy
          CachePolicyId: !Ref PortfolioCachePolicy
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Sub arn:aws:acm:${AWS::Region}:${AWS::AccountId}:certificate/${SSLCertArnDev}
          SslSupportMethod: "sni-only"

  PortfolioCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: !Sub ${AWS::StackName}-cache-policy
        Comment: !Sub "Cache policy for ${ProjectName} Development with compression optimization"
        DefaultTTL: 300    # 5 minutes for dev
        MaxTTL: 86400      # 1 day for dev
        MinTTL: 0
        ParametersInCacheKeyAndForwardedToOrigin:
          EnableAcceptEncodingGzip: true
          EnableAcceptEncodingBrotli: true
          QueryStringsConfig:
            QueryStringBehavior: none
          HeadersConfig:
            HeaderBehavior: whitelist
            Headers:
              - CloudFront-Viewer-Country
          CookiesConfig:
            CookieBehavior: none

  PortfolioHeaderPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: !Sub ${AWS::StackName}-header-policy
        Comment: !Sub "Header policy for ${ProjectName} Development."
        CorsConfig:
          OriginOverride: false
          AccessControlAllowCredentials: false
          AccessControlAllowHeaders:
            Items:
              - ALL
          AccessControlAllowMethods:
            Items:
              - POST
              - GET
              - OPTIONS
              - DELETE
          AccessControlAllowOrigins:
            Items:
            - !Ref HostnameDev
            - !Sub "www.${HostnameDev}"
          AccessControlExposeHeaders:
            Items:
            - ALL
          AccessControlMaxAgeSec: 3600
        RemoveHeadersConfig:
          Items:
            - Header: server
            - Header: x-powered-by
        ServerTimingHeadersConfig:
          Enabled: true
          SamplingRate: 50
        SecurityHeadersConfig:
          StrictTransportSecurity:
            AccessControlMaxAgeSec: 31536000
            IncludeSubdomains: true
            Override: true
          ContentTypeOptions:
            Override: true
          FrameOptions:
            FrameOption: SAMEORIGIN
            Override: true
          ReferrerPolicy:
            Override: true
            ReferrerPolicy: strict-origin-when-cross-origin
          XSSProtection:
            Override: true
            Protection: true
            ModeBlock: true
          ContentSecurityPolicy:
            ContentSecurityPolicy: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://fonts.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https:; frame-ancestors 'none'; base-uri 'self'; form-action 'self';"
            Override: true
        CustomHeadersConfig:
          Items:
            - Header: Permissions-Policy
              Value: "geolocation=(), microphone=(), camera=()"
              Override: true

Outputs:
  UIBucket:
    Value: !Ref UIBucket
    Export:
      Name: !Sub "${AWS::StackName}-UIBucketName"
  CloudFrontDistributionID:
    Value: !Ref PortfolioFrontDistribution
    Export:
      Name: !Sub "${AWS::StackName}-DistributionID"
  CloudFrontURL:
    Value: !Sub "https://${PortfolioFrontDistribution.DomainName}"
    Export:
      Name: !Sub "${AWS::StackName}-CloudFrontURL"
  CustomDomainURL:
    Value: !Sub "https://${HostnameDev}"
    Export:
      Name: !Sub "${AWS::StackName}-CustomDomainURL"