AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation template for Portfolio UI - Production"

Parameters:
  ProjectName:
    Default: portfolio
    Description: "The name of the project. Used as prefix for resource names"
    Type: String

  BucketName:
    Description: "S3 bucket name for UI assets"
    Type: String

  HostnameProd:
    Description: "Custom hostname (optional). Example: example.com"
    Type: String
    Default: ""

  SSLCertArnProd:
    Description: "ACM certificate ARN (must be in us-east-1 for CloudFront). Optional if no custom domain."
    Type: String
    Default: ""

Conditions:
  HasCustomDomain: !And
    - !Not [!Equals [!Ref HostnameProd, ""]]
    - !Not [!Equals [!Ref SSLCertArnProd, ""]]

Resources:
  # ===========================
  # S3 Bucket (PRIVATE)
  # ===========================
  UIBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # ===========================
  # CloudFront OAI (legacy but stable)
  # ===========================
  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "${ProjectName}-Prod-OAI"

  # Bucket policy to allow CloudFront to read S3
  UIBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref UIBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontRead
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId
            Action:
              - s3:GetObject
            Resource: !Sub "arn:aws:s3:::${UIBucket}/*"

  # ===========================
  # Cache Policy: NO CACHE for index.html
  # ===========================
  NoCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: !Sub "${AWS::StackName}-no-cache"
        Comment: "No-cache policy for index.html"
        DefaultTTL: 0
        MaxTTL: 0
        MinTTL: 0
        ParametersInCacheKeyAndForwardedToOrigin:
          EnableAcceptEncodingGzip: false
          EnableAcceptEncodingBrotli: false
          CookiesConfig:
            CookieBehavior: none
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none

  # Cache Policy: Long cache for static assets
  LongCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: !Sub "${AWS::StackName}-long-cache"
        Comment: "Long-cache for versioned assets (JS/CSS/media). Safe due to hashed filenames."
        DefaultTTL: 31536000
        MaxTTL: 31536000
        MinTTL: 1
        ParametersInCacheKeyAndForwardedToOrigin:
          EnableAcceptEncodingGzip: true
          EnableAcceptEncodingBrotli: true
          CookiesConfig:
            CookieBehavior: none
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none

  # ===========================
  # Response Headers Policy (basic + security)
  # ===========================
  PortfolioHeaderPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: !Sub "${AWS::StackName}-headers"
        Comment: "Security headers for Portfolio UI"
        CorsConfig:
          OriginOverride: true
          AccessControlAllowCredentials: false
          AccessControlAllowHeaders:
            Items:
              - "*"
          AccessControlAllowMethods:
            Items:
              - GET
              - HEAD
              - OPTIONS
          AccessControlAllowOrigins:
            Items:
              - "*"
          AccessControlExposeHeaders:
            Items:
              - "*"
          AccessControlMaxAgeSec: 600
        RemoveHeadersConfig:
          Items:
            - Header: server
            - Header: x-powered-by
        SecurityHeadersConfig:
          StrictTransportSecurity:
            AccessControlMaxAgeSec: 31536000
            IncludeSubdomains: true
            Preload: true
            Override: true
          ContentTypeOptions:
            Override: true
          FrameOptions:
            FrameOption: SAMEORIGIN
            Override: true
          ReferrerPolicy:
            ReferrerPolicy: strict-origin-when-cross-origin
            Override: true
          XSSProtection:
            Protection: true
            ModeBlock: true
            Override: true

  # ===========================
  # CloudFront Distribution
  # ===========================
  PortfolioFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub "CloudFront Distribution for ${ProjectName} UI - Production"
        DefaultRootObject: index.html

        Origins:
          - Id: UIOrigin
            DomainName: !GetAtt UIBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}"

        # SPA fallback (React Router)
        CustomErrorResponses:
          - ErrorCode: 403
            ResponsePagePath: /index.html
            ResponseCode: 200
            ErrorCachingMinTTL: 0
          - ErrorCode: 404
            ResponsePagePath: /index.html
            ResponseCode: 200
            ErrorCachingMinTTL: 0

        # Ordered behavior: index.html must be NO-CACHE
        CacheBehaviors:
          - PathPattern: "index.html"
            TargetOriginId: UIOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD, OPTIONS]
            Compress: true
            CachePolicyId: !Ref NoCachePolicy
            ResponseHeadersPolicyId: !Ref PortfolioHeaderPolicy

        # Default behavior: static assets can be cached long
        DefaultCacheBehavior:
          TargetOriginId: UIOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          Compress: true
          CachePolicyId: !Ref LongCachePolicy
          ResponseHeadersPolicyId: !Ref PortfolioHeaderPolicy

        PriceClass: PriceClass_200

        Aliases: !If
          - HasCustomDomain
          - - !Ref HostnameProd
            - !Sub "www.${HostnameProd}"
          - !Ref "AWS::NoValue"

        ViewerCertificate: !If
          - HasCustomDomain
          - AcmCertificateArn: !Sub  arn:aws:acm:${AWS::Region}:${AWS::AccountId}:certificate/${SSLCertArnProd}
            SslSupportMethod: sni-only
            MinimumProtocolVersion: TLSv1.2_2021
          - CloudFrontDefaultCertificate: true

Outputs:
  UIBucketName:
    Value: !Ref UIBucket
    Export:
      Name: !Sub "${AWS::StackName}-UIBucketName"

  CloudFrontDistributionID:
    Value: !Ref PortfolioFrontDistribution
    Export:
      Name: !Sub "${AWS::StackName}-DistributionID"

  CloudFrontURL:
    Value: !Sub "https://${PortfolioFrontDistribution.DomainName}"
    Export:
      Name: !Sub "${AWS::StackName}-CloudFrontURL"

  CustomDomainURL:
    Condition: HasCustomDomain
    Value: !Sub "https://${HostnameProd}"
    Export:
      Name: !Sub "${AWS::StackName}-CustomDomainURL"
